name: Sync to DiaoLab Organization

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.name "monnneee"
        git config --global user.email "yueyuanxu1112@gmail.com"

    - name: Push to DiaoLab Organization Repo
      run: |
        git remote add org https://github.com/DiaoLab/scHiCAR.git
        git push org main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
